In [21]:
import numpy
from sklearn import linear_model

#X represents the size of a tumor in centimeters.
X = numpy.array([3.78, 2.44, 2.09, 0.14, 1.72, 1.65, 4.92, 4.37, 4.96, 4.52, 3.69, 5.88]).reshape(-1,1)

#Note: X has to be reshaped into a column from a row for the LogisticRegression() function to work.
#y represents whether or not the tumor is cancerous (0 for "No", 1 for "Yes").
y = numpy.array([1, 0, 0, 0, 0, 0, 2, 1, 2, 1, 1, 2]) 

logr = linear_model.LogisticRegression()
logr.fit(X,y)

predicted = logr.predict(numpy.array([[0.5, 1, 1.5, 2, 2.5, 3, 3.5, 4, 4.5, 5]]).reshape(-1, 1))
print(predicted)

awds = logr.coef_
odds = numpy.exp(awds)

def af(logr, x):
    awdds = logr.coef_ * x + logr.intercept_
    odd = numpy.exp(awdds)
    prob = odd/(1+odd)
    return prob

print(logr.coef_)
print(logr.intercept_)
print(af(logr, X))

[0 0 0 0 0 0 1 1 1 2]
[[-1.33628243]
 [ 0.1496548 ]
 [ 1.18662763]]
[ 4.75744487  0.09892782 -4.85637269]


ValueError: operands could not be broadcast together with shapes (3,1) (12,1) 

In [6]:
import pandas as pd

data = {
    "Cmds": ['ff', 'ft', 'tt', 'tt', 'tf', 'd', 'd', 'ff'],
    "NotHot": [1, 2, 3, 4, 5, 6, 7, 8]
}

df = pd.DataFrame(data)
print(df)

dumb = pd.get_dummies(df, drop_first=True)
print(dumb)

  Cmds  NotHot
0   ff       1
1   ft       2
2   tt       3
3   tt       4
4   tf       5
5    d       6
6    d       7
7   ff       8
   NotHot  Cmds_ff  Cmds_ft  Cmds_tf  Cmds_tt
0       1     True    False    False    False
1       2    False     True    False    False
2       3    False    False    False     True
3       4    False    False    False     True
4       5    False    False     True    False
5       6    False    False    False    False
6       7    False    False    False    False
7       8     True    False    False    False
